### ISSUE TITLE
affected/package: config.go

### ISSUE THREAD

**Issue by Ashion** [trpc-group/trpc-go#143]
### What version of tRPC-Go are you using?
master

### Does this issue reproduce with the latest release?
yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
I have service on both restful and trpc, and needs the restful listen on all addresses, trpc listen on localhost(127.0.0.1)
it seems cannot work likes this.

1. test the examples/features/restful
2. update configure trpc_go.yaml to
``` yaml
global:                             # global config.
  namespace: Development            # environment type, two types: production and development.
  env_name: test                    # environment name, names of multiple environments in informal settings.

server:                                            # server configuration.
  app: test                                        # business application name.
  server: helloworld                               # service process name.
  bin_path: /usr/local/trpc/bin/                   # paths to binary executables and framework configuration files.
  conf_path: /usr/local/trpc/conf/                 # paths to business configuration files.
  data_path: /usr/local/trpc/data/                 # paths to business data files.
  service:                                         # business service configuration，can have multiple.
    - name: trpc.test.helloworld.Greeter           # the route name of the service.
      # ip: 127.0.0.1                                # the service listening ip address, can use the placeholder ${ip}, choose one of ip and nic, priority ip.
      port: 9092                                   # the service listening port, can use the placeholder ${port}.
      network: tcp                                 # the service listening network type,  tcp or udp.
      protocol: restful                            # application layer protocol. NOTE restful service this is restful.
      timeout: 1000                                # maximum request processing time in milliseconds.
      idletime: 300000                             # connection idle time in milliseconds.
    - name: trpc.test.helloworld.Greeter1           # the route name of the service.
      ip: 127.0.0.1                                # the service listening ip address, can use the placeholder ${ip}, choose one of ip and nic, priority ip.
      port: 9093                                   # the service listening port, can use the placeholder ${port}.
      network: tcp                                 # the service listening network type,  tcp or udp.
      protocol: trpc                            # application layer protocol. NOTE restful service this is restful.
      timeout: 1000                                # maximum request processing time in milliseconds.
      idletime: 300000                             # connection idle time in milliseconds.

plugins:                                          # plugin configuration.
  log:                                            # log configuration.
    default:                                      # default log configuration, support multiple outputs.
      - writer: console                           # console standard output default.
        level: debug                              # standard output log level.

```
4. update main.go to
 ``` go
package main

import (
	"context"
	"fmt"

	trpc "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/examples/features/restful/pb"
	"trpc.group/trpc-go/trpc-go/log"
)

func main() {
	// init trpc server
	server := trpc.NewServer()
	// Register the greeter service with the server
	svc := new(greeterService)
	pb.RegisterGreeterService(server.Service("trpc.test.helloworld.Greeter"), svc)
	pb.RegisterGreeterService(server.Service("trpc.test.helloworld.Greeter1"), svc)
	// Run the server
	if err := server.Serve(); err != nil {
		log.Fatal(err)
	}
}

// greeterService is used to implement pb.GreeterService.
type greeterService struct {
	// unimplementedGreeterServiceServer is the unimplemented greeter service server
	pb.UnimplementedGreeter
}

// SayHello implements pb.GreeterService.
func (g greeterService) SayHello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloReply, error) {
	log.InfoContextf(ctx, "[restful] Received SayHello request with req: %v", req)
	// handle request
	rsp := &pb.HelloReply{
		Message: "[restful] SayHello Hello " + req.Name,
	}
	return rsp, nil
}

// Message implements pb.GreeterService.
func (g greeterService) Message(ctx context.Context, req *pb.MessageRequest) (*pb.MessageInfo, error) {
	log.InfoContextf(ctx, "[restful] Received Message request with req: %v", req)
	// handle request
	rsp := &pb.MessageInfo{
		Message: fmt.Sprintf("[restful] Message name:%s,subfield:%s",
			req.GetName(), req.GetSub().GetSubfield()),
	}
	return rsp, nil
}

// UpdateMessage implements pb.GreeterService.
func (g greeterService) UpdateMessage(ctx context.Context, req *pb.UpdateMessageRequest) (*pb.MessageInfo, error) {
	log.InfoContextf(ctx, "[restful] Received UpdateMessage request with req: %v", req)
	// handle request
	rsp := &pb.MessageInfo{
		Message: fmt.Sprintf("[restful] UpdateMessage message_id:%s,message:%s",
			req.GetMessageId(), req.GetMessage().GetMessage()),
	}
	return rsp, nil
}

// UpdateMessageV2 implements pb.GreeterService.
func (g greeterService) UpdateMessageV2(ctx context.Context, req *pb.UpdateMessageV2Request) (*pb.MessageInfo, error) {
	log.InfoContextf(ctx, "[restful] Received UpdateMessageV2 request with req: %v", req)
	// handle request
	rsp := &pb.MessageInfo{
		Message: fmt.Sprintf("[restful] UpdateMessageV2 message_id:%s,message:%s",
			req.GetMessageId(), req.GetMessage()),
	}
	return rsp, nil
}

```

### What did you expect to see?
trpc.test.helloworld.Greeter listen on :9092
trpc service:trpc.test.helloworld.Greeter1 listen on 127.0.0.1:9093

``` shell
2023-12-11 21:11:51.967	DEBUG	maxprocs/maxprocs.go:47	maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
2023-12-11 21:12:03.947	INFO	server/service.go:167	process:7755, restful service:trpc.test.helloworld.Greeter launch success, tcp::9092, serving ...
2023-12-11 21:12:03.947	INFO	server/service.go:167	process:7755, trpc service:trpc.test.helloworld.Greeter1 launch success, tcp:127.0.0.1:9093, serving ...
```

### What did you see instead?

``` shell
2023-12-11 21:11:51.967	DEBUG	maxprocs/maxprocs.go:47	maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
2023-12-11 21:12:03.947	INFO	server/service.go:167	process:7755, restful service:trpc.test.helloworld.Greeter launch success, tcp:127.0.0.1:9092, serving ...
2023-12-11 21:12:03.947	INFO	server/service.go:167	process:7755, trpc service:trpc.test.helloworld.Greeter1 launch success, tcp:127.0.0.1:9093, serving ...
```
